<?php

/**
 * PluginDemoImageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginDemoImageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginDemoImageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginDemoImage');
    }
}